import { Poppins } from "next/font/google";
import "./globals.css";
import ModeProvider from "./providers/ModeProvider";
import { ThemeContextProvider } from "./context/ThemeContext";
import TranslationProvider from "./providers/TranslationProvider";
import SettingBar from "./ui/bars/SettingBar";
import DateLocalizationProvider from "./providers/DateLocalizationProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Golnia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <TranslationProvider>
          <ModeProvider>
            <DateLocalizationProvider>
              <body className={poppins.className}>
                <SettingBar />
                {children}
              </body>
            </DateLocalizationProvider>
          </ModeProvider>
        </TranslationProvider>
      </ThemeContextProvider>
    </html>
  );
}
